---
- name: deploy django
  become: yes
  hosts: django

  tasks:

    - name: macc.fflch.usp.br
      include_role:
        name: fflch.django
      vars:
        django_name: "macc"
        django_dest: "/var/www/macc"
        django_repo: "https://github.com/fflch/macc.git"
        django_version: "1.0.2"
        django_port: "8002"
        django_envfile: '.env.sample'
        django_pythonversion: '3.10'
        django_env:   
          - name: SECRET_KEY
            value: "123dZdRASw"
          - name: POSTGRES_USER
            value: macc
          - name: POSTGRES_DB
            value: macc
          - name: POSTGRES_HOST
            value: 192.168.8.4
          - name: POSTGRES_PASSWORD
            value: "macc"
