---
- name: deploy vagrantdjango
  become: yes
  hosts: vagrantdjango

  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks
      vars:
        tasks_django: true
