---
- name: vagrant_entrypointbackup
  become: yes
  hosts: vagrantentrypointbackup

  vars:
    entrypointbackup_public_key: "{{ lookup('file', '../../files/sshpublickey.txt') }}"

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_entrypointbackup: true
