---
- name: vagrant_entrypointbackup
  become: yes
  hosts: entrypointbackup

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_entrypointbackup: true
