---
- name: deploy
  become: yes
  hosts: vagrant_firstdc

  #### global vars
  vars:
    backup_directories:
      - /etc
    # variables to smb.conf template used at sambadc role
    template_smb_cups_server    : '192.168.8.43:631'
    template_smb_netbios        : "{{ inventory_hostname }}"
    sambadc_realm: "smbdomain.fflch.usp.br"
    printersfile: "{{ lookup('file', '../../files/printers.csv') }}"
    printers: "{{ printersfile.split('\n') }}"
    template_smb_dns_forwarder: 8.8.8.8
    template_printers: []

  #### tasks
  tasks:

    - name: monta lista de dicionários cups_printer_list
      set_fact: 
        template_printers: > 
          {{ template_printers + [{ 
            'name': item.split(',')[0]
          }]}}
      with_items: 
        - "{{ printers }}"

    - name: configura /etc/hosts e /etc/hostnane
      include_role:
        name: Stouts.hostname
      vars:
        hostname_hostname: "{{ inventory_hostname }}.{{sambadc_realm}}"

    - name: Common tasks across all FFLCH servers
      import_tasks: ../tasks/common.yml

    - name: Samba DC common tasks
      import_tasks: ../tasks/sambadc.yml

    - name: Configura samba como um Domain Controller
      include_role:
        name: fflch.sambadc
      vars:
        sambadc_type: "new"
        sambadc_realm: "smbdomain.fflch.usp.br"
        sambadc_admin_password: "{{ lookup('passwordstore', 'sti/servidores/smbdomain/Administrator/password') }}"
        sambadc_smb_path: "{{ playbook_dir }}/../../templates/smb.conf.j2"
 
    - name: Configura resolv.conf para consultar DNSs no próprio samba
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 192.168.8.48
        resolv_conf_search_domains:
          - "{{ sambadc_realm }}"
