---
- name: freeradius
  become: yes
  hosts: freeradius

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_freeradius: true

##############
# Dicas para testar
# insert into radcheck (username,attribute,op,value) values("maria", "Cleartext-Password", ":=", "m123");
# radtest maria m123 localhost 0 mysecret
# tail -f /var/log/freeradius/radius.log

