---
- name: mariadbmaster
  become: yes
  hosts: vagrant_mariadbmaster

  vars_prompt:
    - name: msmtp_password
      prompt: Senha do email de smtp?

  vars:
    msmtp_email: 'noreplay.fflch@usp.br'
      
  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks

    - name: Instala Mysql e cria dbs/users
      include_role:
        name: geerlingguy.mysql
      vars:
        mysql_root_username: root
        mysql_root_password: "SuperPassw0rd"
        mysql_bind_address: '*'
        mysql_mysqldump_max_allowed_packet: "1024M"
        mysql_users:
          - name: aegir_root
            host: "%"
            password: "SuperPassw0rd"
            priv: "*.*:ALL,GRANT"    