---
- name: postgresql
  become: yes
  hosts: postgresql
     
  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks

    - name: Instala postgresql e cria dbs e users
      include_role:
        name: geerlingguy.postgresql
      vars:
        postgresql_locales:
          - 'pt_BR.UTF-8'
        postgresql_hba_entries:
          - { type: local, database: all, user: postgres, auth_method: peer }
          - { type: local, database: all, user: all, auth_method: peer }
          - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
          - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
          - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
        postgresql_global_config_options:
          - option: unix_socket_directories
            value: '{{ postgresql_unix_socket_directories | join(",") }}'
          - option: log_directory
            value: 'log'
          - option: listen_addresses
            value: '*'

        postgresql_users:
          - name: admin
            password: 'admin'
            encrypted: True
            role_attr_flags: SUPERUSER
            db: template1
            port: 5432

          - name: macc
            password: 'macc'
            encrypted: True
            db: macc
            port: 5432

        postgresql_databases:
           - name: macc
             owner: macc
             lc_collate: 'pt_BR.UTF-8'
             lc_ctype: 'pt_BR.UTF-8'

    - name: Aplica role fflch.tasks 
      include_role:
        name: ome.postgresql_backup
      vars:
        postgresql_backup_dir: /backupspostgresql

# Testando conexão do hospedeiro:
# sudo apt install postgresql-client
# PGPASSWORD='macc' psql -h 192.168.8.4 -U macc -d macc

# PGPASSWORD='admin' psql -h 192.168.8.4 -U admin -d template1
# \l
