- name: deploy rshiny
  become: yes
  hosts: rshiny

  vars:
    backup_directories:
      - /etc/bind

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks

    - name: Install a list of R packages for projects
      apt:
        pkg:
        - r-base
        - r-cran-shinythemes
        - r-cran-tidyverse
        - r-cran-shiny
        - r-cran-dt
        - r-cran-markdown
        - r-cran-stringr

    - name: Clone django project repository
      git:
        repo: "https://github.com/brunomaroneze/dicio_biologia.git"
        dest: "/dicio_biologia"
        version: master
        force: yes
        update: yes

    - name: Aplica role rshiny
      include_role:
        name: oefenweb.shiny_server
      vars:
        shiny_server_conf_directives:
          - |
            run_as shiny;
            server {
              listen 3838;
              location / {
                site_dir /dicio_biologia;
                log_dir /var/log/shiny-server;
                directory_index on;
              }
            }

    - name: Recursively change ownership
      file:
        path: "/dicio_biologia"
        owner: "shiny"
        group: "shiny"

# Acessar na web: http://192.168.8.3:3838/
#
