---
- name: vagrant_rsyslog
  become: yes
  hosts: vagrantrsyslog

  vars:
    backup_directories:
      - /etc
    rsyslog_ip_laravel: 192.168.8.92
    rsyslog_emails:
      - {email: 'servidor1@usp.br'}
      - {email: 'servidor2@usp.br'}
      - {email: 'servidor3@usp.br'}
      - {email: 'servidor4@usp.br'}

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_rsyslog: true

    - name: robertdebock.rsyslog
      include_role:
        name: robertdebock.rsyslog
      vars:
        rsyslog_receiver: yes
        rsyslog_config_file_format: advanced

    - name: robertdebock.logrotate
      include_role:
        name: robertdebock.logrotate
      vars:
        logrotate_frequency: daily
        logrotate_keep: 100
        logrotate_compress: yes
        logrotate_user: root
        logrotate_group: root
        logrotate_entries:
          - name: redelocal
            path: "/var/syslog/hosts/**/**/**/**/*.log"
          - name: nuvem
            path: "/var/syslog/hosts/**/**/**/**/**/*.log"

