---
- name: vagrant_rsyslog
  become: yes
  hosts: rsyslog

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_rsyslog: true

    - name: robertdebock.rsyslog
      include_role:
        name: robertdebock.rsyslog
      vars:
        rsyslog_receiver: yes
        rsyslog_config_file_format: advanced

    - name: robertdebock.logrotate
      include_role:
        name: robertdebock.logrotate
      vars:
        logrotate_frequency: daily
        logrotate_keep: 100
        logrotate_compress: yes
        logrotate_user: root
        logrotate_group: root
        logrotate_entries:
          - name: redelocal
            path: "/var/syslog/hosts/**/**/**/**/*.log"
          - name: nuvem
            path: "/var/syslog/hosts/**/**/**/**/**/*.log"

