---
- name: deploy vagrant_zoneminder
  become: yes
  hosts: zoneminder

  vars:
    backup_directories:
      - /etc

    # mysql
    mysql_root:
      username: aegir_root
      password: "SuperPassw0rd"

    tasks_zoneminder_apache2_confs: zoneminder
    tasks_zoneminder_version: '1.36'
    tasks_zoneminder_frontend_url: 'zm.local.fflch.usp.br'
    tasks_zoneminder_mysql:
      database: zm
      host: '192.168.8.10'
      user: zm
      password: 'zm'

  tasks:

    - name: Role que corrige hostname da máquina
      include_role:
        name: Stouts.hostname
      vars:
        hostname_hostname: "{{ tasks_zoneminder_frontend_url }}"

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_php: true
        tasks_zoneminder: true
